### ISSUE TITLE
Any project updates?

### ISSUE THREAD

**Issue by stefanos82** [jegoyalu/jariscms#1]
@jgmdev any project updates mate?

Why haven't you sync the code for more than a year now?

Now it's your chance to attract new candidates; WordPress has messed up badly with its new JS-based editor, page-builder-wanna-be and the community has reacted furiously.

There is even a fork named [ClassicPress](https://www.classicpress.net/).

Can you sync your code and share it on Hacker News? I'm sure people will find it interesting.

Let me know what you think.

**Comment by jgmdev** [comment]
Hey bro! 

Thanks for keeping me updated, I wasn't aware of the situation on the wordpress camp. I wonder what is bad about that new drag and drop page editor... In any case, I have been refactoring jaris code and modules to make it more stricter and have discovered so far a can of bugs that went unnoticed due to the scripting nature of PHP which now can be mitigated with type hints. So I'm trying to leverage the type hints and in the road fix any issues that I find.

**Comment by stefanos82** [comment]
On Sun, 02 Sep 2018 19:35:17 -0700
Jefferson González <notifications@github.com> wrote:

> Hey bro! 
> 
> Thanks for keeping me updated, I wasn't aware of the situation on the wordpress camp. I wonder what is bad about that new drag and drop page editor... In any case, I have been refactoring jaris code and modules to make it more stricter and have discovered so far a can of bugs that went unnoticed due to the scripting nature of PHP which now can be mitigated with type hints. So I'm trying to leverage the type hints and in the road fix any issues that I find.

Finish currently what you are doing and sync it. DON'T LOSE THIS CHANCE!

Now it's your opportunity! People want to offer their customers an alternative option that is easy as WordPress.

The new WP editor is not exactly an editor. It directly competes with Wix, Medium, and Squarespace as it is implemented. They also plan to make it much more like page builder than as a traditional word editor.

The community is not pleased at all!

Matt Mullenweg cares about satisfying his investors and completely ignores the wordpress.org community that helped WordPress becoming the platform that is today.

Like...why do we, the WP community, should care about Automattic's financial investments, about how they do their proprietary business?

It's absolutely absurd.

> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jegoyalu/jariscms/issues/1#issuecomment-417984617


-- 
Stefanos Sofroniou <sofr.stef@cytanet.com.cy>

**Comment by stefanos82** [comment]
On Mon, 03 Sep 2018 16:25:18 -0700
Jefferson González <notifications@github.com> wrote:

> I guess that if they keep the ability to work directly with the content html/css/js it shouldn't be a big issue for developers that make use of wordpress and want that extra functionality. But, I think this trend to develop tools which obsolete web developers and which tries to make anyone capable of developing web solutions is which triggered that whole wordpress ruckus. 
> 
> At the end it seems something inevitable, making an informative website will be something that anyone can do (thanks to the greed of big corps), like it or not for those like me involved in this business, will have to keep evolving and doing what this tools can't, which is everything related to custom programming. For me as I have told you before, developing a content management system besides been a tool that I can completely know and shape is a great learning experience, that has helped me learn various technologies involved.
> 
> And Yes! I have to sync my code, but still, I feel like my code sucks and that most people will not like it and it will just be target for criticism :( Theres a lot of stuff that I would make differently if I was given the opportunity to start from scratch...
> 

Comparing WordPress's codebase, your programming style is pure poetry!

It's time to start believing in yourself mate.

You are just suffering from Impostor Syndrome as much as I.

> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jegoyalu/jariscms/issues/1#issuecomment-418204783


-- 
Stefanos Sofroniou <sofr.stef@cytanet.com.cy>
